function k(b,a,c,d){b.u.Hb(b.lb,a,c,d,void 0)}function l(b,a,c,d){b.u.ma?k(b,a,c,d):b.u.Ee()._OnMessageFromDOM({type:"event",component:b.lb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.u.D(b.lb,a,c)}function t(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Tb||(b.u.xe(b.Ud),b.Tb=!0)}window.eb=class{constructor(b,a){this.u=b;this.lb=a;this.Tb=!1;this.Ud=()=>this.La()}ed(){}La(){}};function aa(b){-1!==b.$a&&(self.clearTimeout(b.$a),b.$a=-1)}
window.ue=class{constructor(b){this.Kc=b;this.Se=5;this.$a=-1;this.Wb=-Infinity;this.Vd=()=>{this.$a=-1;this.Wb=Date.now();this.qb=!0;this.Kc();this.qb=!1};this.xd=this.qb=!1}j(){aa(this);this.Vd=this.Kc=null}};"use strict";
function ba(b,a){const c=a.elementId,d=b.jd(c,a);b.da.set(c,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");a=b.zc(d);a.addEventListener("focus",()=>{ca(b,"elem-focused",c)});a.addEventListener("blur",()=>{ca(b,"elem-blurred",c)});b.Pb&&document.body.appendChild(d)}function da(b,a){n(b,"get-element",c=>{const d=b.da.get(c.elementId);return a(d,c)})}function ca(b,a,c){var d;d||(d={});d.elementId=c;k(b,a,d)}
window.ne=class extends self.eb{constructor(b){super(b,"button");this.da=new Map;this.Pb=!0;t(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const c=this.da.get(a);this.Pb&&c.parentElement.removeChild(c);this.da.delete(a)}],["set-visible",a=>{this.Pb&&(this.da.get(a.elementId).style.display=a.isVisible?"":"none")}],["update-position",a=>{if(this.Pb){var c=this.da.get(a.elementId);c.style.left=a.left+"px";c.style.top=a.top+"px";c.style.width=a.width+"px";c.style.height=a.height+"px";a=
a.fontSize;null!==a&&(c.style.fontSize=a+"em")}}],["update-state",a=>{const c=this.da.get(a.elementId);this.wc(c,a)}],["focus",a=>this.Fc(a)],["set-css-style",a=>{const c=this.da.get(a.elementId),d=a.prop;a=a.val;d.startsWith("--")?c.style.setProperty(d,a):c.style[d]=a}],["set-attribute",a=>{this.da.get(a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{this.da.get(a.elementId).removeAttribute(a.name)}]]);da(this,a=>a)}jd(){throw Error("required override");}wc(){throw Error("required override");
}zc(b){return b}Fc(b){const a=this.zc(this.da.get(b.elementId));b.focus?a.focus():a.blur()}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),v=/android/i.test(navigator.userAgent);let fa=0;
function w(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.bf?new Promise(c=>{const d="c3_resolve_"+fa;++fa;self[d]=c;a.textContent=b.ff+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ha=!1,ia=!1;function ja(){if(!ha){try{new Worker("blob://",{get type(){ia=!0}})}catch(b){}ha=!0}return ia}let y=new Audio;
const ka={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;async function na(b){b=await oa(b);return(new TextDecoder("utf-8")).decode(b)}
function oa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const z=[];let C=0;window.RealFile=window.File;const D=[],F=new Map,G=new Map;let pa=0;const qa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");qa.push(b)};const ra=new Set(["cordova","playable-ad","instant-games"]);let sa=!1;
window.ua=class b{constructor(a){this.ma=a.hf;this.wa=null;this.ba="";this.Ya=a.ef;this.Eb={};this.Ra=this.ta=null;this.Rb=[];this.J=this.xa=null;this.Sc=!1;this.Bd=0;this.sb=null;this.Xa=-1;this.Xe=()=>this.Le();this.Wa=[];this.A=a.Wd;this.Ub="file"===location.protocol.substr(0,4);!this.ma||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ja()||(this.ma=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ma=!1;if("cordova"===this.A&&this.ma)if(v){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ma=!1)}else this.ma=!1;this.Yb=this.qa=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.D("runtime","cordova-fetch-local-file",c=>this.He(c));this.D("runtime","create-job-worker",()=>this.Ie());"cordova"===this.A?document.addEventListener("deviceready",()=>this.qd(a)):this.qd(a)}j(){this.xc();
this.wa&&(this.wa=this.wa.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Ra&&(this.Ra.j(),this.Ra=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}re(){return ea&&"cordova"===this.A}sc(){const a=navigator.userAgent;return ea&&ra.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}pe(){return v}ld(){return v&&ra.has(this.A)}async qd(a){"macos-wkwebview"===this.A&&this.Ic({type:"ready"});if("playable-ad"===this.A){this.qa=self.c3_base64files;
this.Yb={};await this.Ae();for(let d=0,e=a.ab.length;d<e;++d){var c=a.ab[d];this.Yb.hasOwnProperty(c)?a.ab[d]={bf:!0,ff:this.Yb[c]}:this.qa.hasOwnProperty(c)&&(a.ab[d]=URL.createObjectURL(this.qa[c]))}}a.df?this.ba=a.df:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.kf&&(this.Eb=a.kf);c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.Ke(d));this.sb=new self.se(this);await ta(this.sb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ma?await this.Ge(a,c.port2):await this.Fe(a,c.port2)}Ac(a){a=this.Eb.hasOwnProperty(a)?this.Eb[a]:a.endsWith("/workermain.js")&&this.Eb.hasOwnProperty("workermain.js")?
this.Eb["workermain.js"]:"playable-ad"===this.A&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async nc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Ub)return a=await this.Fb(d.af?a:this.Ya+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ha(){return Math.max(window.innerHeight,1)}pd(a){var c=this.ba,d=location.href,e=this.oa(),f=this.ha(),g=window.devicePixelRatio,h=b.hb(),m=a.rf,q=window.cr_previewImageBlobs||this.qa,p=window.cr_previewProjectFileBlobs,A=window.cr_previewProjectFiles,x=window.pf||"";a=a.Wd;var r=(new URLSearchParams(self.location.search)).has("debug"),B=this.sb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,
isFullscreen:h,projectData:m,previewImageBlobs:q,previewProjectFileBlobs:p,previewProjectFileSWUrls:A,swClientId:x,exportType:a,isDebug:r,ife:!!self.qf,jobScheduler:{inputPort:B.Rc,outputPort:B.Yc,maxNumWorkers:B.Ue},supportedAudioFormats:ka,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Ya+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Ya+"opus.wasm.wasm",isFileProtocol:this.Ub,isiOSCordova:this.re(),isiOSWebView:this.sc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ge(a,
c){const d=this.Ac(a.jf);"preview"===this.A?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,m)=>{const q=p=>{this.ta.removeEventListener("message",q);p.data&&"ok"===p.data.type?h():m()};this.ta.addEventListener("message",q);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,this.ba)).toString()})})):this.ta=await this.nc(d,this.ba,{type:"module",name:"Runtime",af:!0});this.J=document.createElement("canvas");this.J.style.display="none";
const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.dd||[],g=a.ab;f=await Promise.all(f.map(h=>this.Ma(h)));g=await Promise.all(g.map(h=>this.Ma(h)));if("cordova"===this.A)for(let h=0,m=a.lc.length;h<m;++h){const q=a.lc[h],p=q[0];if(p===a.bd||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))q[1]=await this.Ma(p)}this.ta.postMessage(Object.assign(this.pd(a),{type:"init-runtime",
isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.lc,mainProjectScript:a.bd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...va(this.sb)]);this.Rb=D.map(h=>new h(this));this.od();wa(this.xa);self.c3_callFunction=(h,m)=>{var q=this.xa;return q.u.nd(q.lb,"js-invoke-function",{name:h,params:m},void 0,void 0)};"preview"===this.A&&(self.goToLastErrorScript=()=>this.Hb("runtime","go-to-last-error-script"))}async Fe(a,c){this.J=document.createElement("canvas");
this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Rb=D.map(g=>new g(this));this.od();var d=a.ab.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.dd)&&d.unshift(...a.dd);d=await Promise.all(d.map(g=>this.Ma(g)));await Promise.all(d.map(g=>w(g)));d=self.C3_ProjectScriptsStatus;const e=a.bd,f=a.lc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ma(h),await w(h),"preview"!==
this.A||d[g]||this.sd(g,"main script did not run to completion")}catch(m){this.sd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ma(h),await w(h);"preview"===this.A&&"object"!==typeof self.lf.mf?(this.Lb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.pd(a),
{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:qa}),wa(this.xa),this.rd(),this.Ra=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ra,a))}sd(a,c){this.Lb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}rd(){this.Lb()}Lb(){const a=window.Ze;a&&(a.parentElement.removeChild(a),window.Ze=null)}async Ie(){const a=
await xa(this.sb);return{outputPort:a,transferables:[a]}}Ee(){if(this.ma)throw Error("not available in worker mode");return this.Ra}Hb(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}nd(a,c,d,e,f){const g=pa++,h=new Promise((m,q)=>{G.set(g,{resolve:m,reject:q})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Je(a);
if("result"===c)this.Me(a);else if("runtime-ready"===c)this.Ne();else if("alert-error"===c)this.Lb(),alert(a.message);else if("creating-runtime"===c)this.rd();else throw Error(`unknown message '${c}'`);}Je(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Kb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Kb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,
h);this.Kb(f,!1,""+h)}):this.Kb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Kb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Me(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}D(a,c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
e.set(c,d)}static bb(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}od(){for(const a of this.Rb)if("runtime"===a.lb){this.xa=a;return}throw Error("cannot find runtime DOM handler");}Ke(a){this.Hb("debugger","message",a)}Ne(){for(const a of this.Rb)a.ed()}static hb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||sa)}static Mb(a){sa=!!a}xe(a){this.Wa.push(a);this.Hc()}Pe(a){a=this.Wa.indexOf(a);if(-1===a)throw Error("invalid callback");
this.Wa.splice(a,1);this.Wa.length||this.xc()}Hc(){-1===this.Xa&&this.Wa.length&&(this.Xa=requestAnimationFrame(this.Xe))}xc(){-1!==this.Xa&&(cancelAnimationFrame(this.Xa),this.Xa=-1)}Le(){this.Xa=-1;for(const a of this.Wa)a();this.Hc()}Ca(a){this.xa.Ca(a)}Ka(a){this.xa.Ka(a)}Gc(){this.xa.Gc()}Jb(a){this.xa.Jb(a)}qe(){return!!ka["audio/webm; codecs=opus"]}async Qe(a){a=await this.nd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}ve(a){this.Sc=!0;this.Bd=a}oe(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||
"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}md(a){return!this.oe(a)}async Ma(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Ub&&this.md(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Fb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async He(a){const c=a.filename;switch(a.as){case "text":return await this.me(c);case "buffer":return await this.Fb(c);default:throw Error("unsupported type");}}hd(a){const c=window.cordova.file.applicationDirectory+
"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async me(a){a=await this.hd(a);return await na(a)}yc(){if(z.length&&!(8<=C)){C++;var a=z.shift();this.Be(a.filename,a.gf,a.$e)}}Fb(a){return new Promise((c,d)=>{z.push({filename:a,gf:e=>{C--;this.yc();c(e)},$e:e=>{C--;this.yc();d(e)}});this.yc()})}async Be(a,c,d){try{const e=await this.hd(a),f=await oa(e);c(f)}catch(e){d(e)}}Ic(a){if("windows-webview2"===this.A)window.chrome.webview.postMessage(JSON.stringify(a));
else if("macos-wkwebview"===this.A)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async Ae(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.ze(c,d));await Promise.all(a)}async ze(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.Yb[a]=c.str;else{let d=await this.De(c);d||(d=this.Ce(c));this.qa[a]=d}}async De(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Ce(a){a=this.Oe(a);return this.ye(a.data,a.cf)}Oe(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{cf:a,data:d}}ye(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=
3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const H=self.ua;function ya(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const za=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Aa={dispatchUserScriptEvent:!0},Ba={dispatchRuntimeEvent:!0};
function Ca(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Da(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await Da(b)}finally{URL.revokeObjectURL(b)}}
function Ea(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Fa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Ea(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ga(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ha=new Set(["input","textarea","datalist","select"]),Ia=new Set(["canvas","body","html"]);function K(b){Ia.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ja(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Fa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ka=!1;document.addEventListener("pause",()=>Ka=!0);document.addEventListener("resume",()=>Ka=!1);function wa(b){b.Ad=!0;b.Vc=b.u.oa();b.tb=b.u.ha()}async function La(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ma(b){return await self.C3_GetSvgImageSize(b.blob)}
function Na(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Oa(b){self.setTimeout(()=>{b.zd=!0},1E3);"cordova"===b.u.A?(document.addEventListener("pause",()=>Pa(b,!0)),document.addEventListener("resume",()=>Pa(b,!1))):document.addEventListener("visibilitychange",()=>Pa(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ka)}}
function Qa(b){b.ud||(b.ud=!0,window.addEventListener("deviceorientation",a=>{b.Z||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Ra(b){b.td||(b.td=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Sa(b){await Ca(b.url)}
function Ta(b,a){b.Cd=a.message;-1===b.Nc&&(b.Nc=setTimeout(()=>{b.Nc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Cd)},250))}function L(b){if(!b.Z){var a=H.hb();a&&"any"!==b.$c&&Ua(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ha()})}}function Va(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:H.hb(),innerWidth:b.oa(),innerHeight:b.ha()})}
function Pa(b,a){a?b.u.xc():b.u.Hc();k(b,"visibilitychange",{hidden:a})}function Wa(b,a,c){"Backspace"===c.key&&K(c);if(!b.Z){var d=za.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function Xa(b,a,c,d){b.Z||ya(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Ya(b){window!==window.top&&window.focus();Za(b.target)&&document.activeElement&&!Za(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.Z){if(b.Bb&&"pointermove"!==a){var d=b.Bb;d.qb||(aa(d),d.Wb=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.yb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:(c.movementX||0)+b.ec,movementY:(c.movementY||0)+b.fc,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||
0,twist:c.twist||0,timeStamp:c.timeStamp},I);b.ec=0;b.fc=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Xa(b,d,c,Aa),b.yb=c.buttons)}}
function $a(b,a,c){if(!b.Z&&!ya(c)){var d=b.yb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.ca,pageX:c.pageX,pageY:c.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.yb=c.buttons;Xa(b,c.type,c,Aa)}}
function N(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.ca,pageX:f.pageX,pageY:f.pageY+b.ca,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function ab(b,a,c){document.body.style.transform="";b.ca=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.ca=a))}}function bb(b,a,c,d){const e=b.oa(),f=b.ha();b.Za=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.hb()}):10>d&&db(b,e,f,d+1)}
function db(b,a,c,d){-1!==b.Za&&clearTimeout(b.Za);b.Za=setTimeout(()=>bb(b,a,c,d),48)}
function Ua(b){b=b.$c;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Za(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.bb(class extends self.eb{constructor(b){super(b,"runtime");this.Hd=!0;this.Ad=!1;this.Za=-1;this.$c="any";this.td=this.ud=!1;this.Fa=null;this.Z=!1;this.Cd="";this.Nc=-1;this.Qa=this.Bb=null;this.fc=this.ec=0;this.zd=!1;this.Vc=b.oa();this.tb=b.ha();this.ca=this.Db=0;b.D("canvas","update-size",d=>{var e=this.u;e.Sc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",
d.displayScale),this.Hd&&(e.style.display="",this.Hd=!1))});b.D("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.D("runtime","raster-svg-image",d=>La(d));b.D("runtime","get-svg-image-size",d=>Ma(d));b.D("runtime","set-target-orientation",d=>{this.$c=d.targetOrientation});b.D("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.D("runtime",
"post-to-debugger",d=>Na(d));b.D("runtime","go-to-script",d=>Na(d));b.D("runtime","before-start-ticking",()=>Oa(this));b.D("runtime","debug-highlight",d=>{if(d.show){this.Fa||(this.Fa=document.createElement("div"),this.Fa.id="inspectOutline",document.body.appendChild(this.Fa));var e=this.Fa;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Fa&&(this.Fa.style.display="none")});b.D("runtime",
"enable-device-orientation",()=>Qa(this));b.D("runtime","enable-device-motion",()=>Ra(this));b.D("runtime","add-stylesheet",d=>Sa(d));b.D("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.D("runtime","alert",d=>this.Dc(d));b.D("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.D("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=document.createElement("h1");
e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.u.J.style.display="";this.u.ve(d.duration)});b.D("runtime","export-to-video-progress",d=>Ta(this,d));b.D("runtime","exported-to-video",d=>{window.Ye({type:"exported-video",blob:d.blob,time:d.time})});b.D("runtime","exported-to-image-sequence",d=>{window.Ye({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);
window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ga(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.yb=
0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ja,{passive:!1});window.addEventListener("wheel",Ja,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.Z&&this.Ad){var d=this.oa();var e=this.ha();if(this.u.ld()){if(this.zd){if(this.Vc===d&&e<this.tb){this.Db=this.tb-e;ab(this,this.tb,this.Db);d=void 0;break a}0<this.Db&&(this.Db=0,ab(this,e,this.Db))}this.Vc=d;this.tb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,
devicePixelRatio:window.devicePixelRatio,isFullscreen:H.hb()});this.u.sc()&&(-1!==this.Za&&clearTimeout(this.Za),bb(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",()=>L(this));window.addEventListener("mozfullscreenchange",()=>L(this));window.addEventListener("fullscreenerror",d=>Va(this,d));window.addEventListener("webkitfullscreenerror",d=>Va(this,d));window.addEventListener("mozfullscreenerror",d=>Va(this,
d));if(b.sc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ga(f)}else d=!1}d||(document.scrollingElement.scrollTop=
0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.Mb(!0),L(this)):"exited-fullscreen"===d?(H.Mb(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Sa=new Set;this.$b=new WeakSet;this.va=!1}ed(){window.addEventListener("focus",()=>{k(this,"window-focus",null,Ba)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},Ba);this.yb=0});window.addEventListener("focusin",a=>{a=a.target;
(Ha.has(a.tagName.toLowerCase())||Ga(a))&&k(this,"keyboard-blur",null,Ba)});window.addEventListener("keydown",a=>Wa(this,"keydown",a));window.addEventListener("keyup",a=>Wa(this,"keyup",a));window.addEventListener("dblclick",a=>Xa(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.Z||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.ca,pageX:a.pageX,pageY:a.pageY+this.ca,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==
typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Ya(a);M(this,"pointerdown",a)}),this.u.ma&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.Bb=new self.ue(()=>{M(this,"pointermove",this.Qa);this.Qa=null}),this.Bb.xd=!0,window.addEventListener("pointerrawupdate",a=>{this.Qa&&(this.ec+=this.Qa.movementX||0,this.fc+=this.Qa.movementY||0);this.Qa=a;a=this.Bb;if(-1===a.$a){var c=Date.now(),d=c-a.Wb,e=a.Se;d>=e&&a.xd?(a.Wb=c,a.qb=!0,a.Kc(),a.qb=!1):a.$a=self.setTimeout(a.Vd,
Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Ya(a);$a(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>$a(this,"pointermove",a)),window.addEventListener("mouseup",a=>$a(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Ya(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",
a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=()=>this.Gc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.u.pe()&&!this.u.ld()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",
()=>{ab(this,this.ha(),navigator.virtualKeyboard.boundingRect.height)}))}oa(){return this.u.oa()}ha(){return this.u.ha()}Gc(){var b=[...this.Sa];this.Sa.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.$b.has(a)||this.Sa.add(a)})}Ca(b){if("function"!==typeof b.play)throw Error("missing play function");this.$b.delete(b);let a;try{a=b.play()}catch(c){this.Sa.add(b);return}a&&a.catch(()=>{this.$b.has(b)||this.Sa.add(b)})}Ka(b){this.Sa.delete(b);this.$b.add(b)}Jb(b){this.va=!!b}Dc(b){alert(b.message)}});
"use strict";async function ta(b){if(b.Re)throw Error("already initialised");b.Re=!0;var a=b.ya.Ac(("playable-ad"===b.ya.A?b.ya.Ya:"")+"dispatchworker.js");b.Mc=await b.ya.nc(a,b.kb,{name:"DispatchWorker"});a=new MessageChannel;b.Rc=a.port1;b.Mc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Yc=await xa(b)}function va(b){return[b.Rc,b.Yc]}
async function xa(b){const a=b.Id.length;var c=b.ya.Ac(("playable-ad"===b.ya.A?b.ya.Ya:"")+"jobworker.js");c=await b.ya.nc(c,b.kb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Mc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Id.push(c);return e.port1}
self.se=class{constructor(b){this.ya=b;this.kb=b.ba;this.kb="preview"===b.A?this.kb+"workers/":this.kb+b.Ya;this.Ue=Math.min(navigator.hardwareConcurrency||2,16);this.Mc=null;this.Id=[];this.Yc=this.Rc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ua({hf:!0,jf:"workermain.js",ab:["scripts/c3runtime.js"],lc:[],bd:"",ef:"scripts/",dd:[],Wd:"html5"}));"use strict";
async function fb(b,a){a=a.type;let c=!0;0===a?c=await gb():1===a&&(c=await hb());k(b,"permission-result",{type:a,result:c})}async function gb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function hb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ua.bb(class extends self.eb{constructor(b){super(b,"touch");n(this,"request-permission",a=>fb(this,a))}});"use strict";function O(b){b.stopPropagation()}
self.ua.bb(class extends self.ne{constructor(b){super(b)}jd(b,a){const c=document.createElement("input");var d=c;a.isCheckbox?(c.type="checkbox",d=document.createElement("label"),d.appendChild(c),d.appendChild(document.createTextNode("")),d.style.fontFamily="sans-serif",d.style.userSelect="none",d.style.webkitUserSelect="none",d.style.display="inline-block",d.style.color="black"):c.type="button";d.style.position="absolute";d.addEventListener("pointerdown",O);d.addEventListener("pointermove",O);d.addEventListener("pointerrawupdate",
O);d.addEventListener("pointerup",O);d.addEventListener("mousedown",O);d.addEventListener("mouseup",O);d.addEventListener("keydown",O);d.addEventListener("keyup",O);c.addEventListener("click",()=>{var e={isChecked:c.checked};e.elementId=b;l(this,"click",e)});a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.wc(d,a);return d}zc(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}wc(b,a){const c="input"===b.tagName.toLowerCase()?b:b.firstChild;c.checked=a.isChecked;c.disabled=!a.isEnabled;
b.title=a.title;b===c?c.value=a.text:b.lastChild.textContent=a.text}});"use strict";const ib=180/Math.PI;
async function jb(b,a){if(a.isiOSCordova||a.isSafari)b.cc=!0;b.ad=a.timeScaleMode;b.Nd=["equalpower","HRTF","soundfield"][a.panningModel];b.yd=["linear","inverse","exponential"][a.distanceModel];b.Od=a.refDistance;b.Md=a.maxDistance;b.Qd=a.rolloffFactor;if(b.u.Sc)b.cc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.u.Bd)});else{var c={latencyHint:a.latencyHint};b.Td||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");kb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&kb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Oa=b.g.createGain();b.Oa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function lb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,q=a.pos,p=a.panning,A=a.stereoPan;let x=a.off;0<x&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+b.g.currentTime);b.Jd=g;mb(b,g);try{b.$=await nb(b,c,d,e,g,f);if(p){Q(b.$,!0);var r=b.$,B=p.innerAngle,la=p.outerAngle,ma=p.outerGain;if(r.rb){ob(r,p.x,p.y,p.angle);var E=self.cb.we;r.ra[0]!==E(B)&&(r.ra[0]=E(B),
r.F.coneInnerAngle=E(B));r.ra[1]!==E(la)&&(r.ra[1]=E(la),r.F.coneOuterAngle=E(la));r.ra[2]!==ma&&(r.ra[2]=ma,r.F.coneOuterGain=ma)}p.hasOwnProperty("uid")&&(b.$.pa=p.uid)}else"number"===typeof A&&0!==A?(R(b.$,!0),pb(b.$,A)):(Q(b.$,!1),R(b.$,!1));b.$.Play(h,m,q,x)}catch(Bb){console.error("[Construct] Audio: error starting playback: ",Bb);return}finally{c=b.Ab.get(g);if(!c)throw Error("expected pending tag");c.cd--;0===c.cd&&(c.resolve(),b.Ab.delete(g))}u(b)}
async function qb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await rb(b,c);for(const p of S(b,c)){c=p;var f=d,g=e,h=a;if(!c.Pa){var m=c.G.gain;m.cancelScheduledValues(0);var q=c.s.g.currentTime;g=q+g;m.setValueAtTime(m.value,q);m.linearRampToValueAtTime(f,g);c.Ia=f;c.ob=g;c.Sd=h}}T(b)}async function sb(b,a){const c=a.tag;a=a.rate;await rb(b,c);for(const d of S(b,c))b=d,b.la!==a&&(b.la=a,b.Da())}
async function tb(b,a){const c=a.tag;a=a.pos;await rb(b,c);for(const d of S(b,c))d.tc(a)}async function ub(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await nb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function vb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ja.indexOf(a),-1!==a&&b.ja.splice(a,1)}
async function wb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.be(b,...e);else if("delay"===c)e=new self.$d(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Zd(b,c.ia,...e);var f=a.bufferType;c.vd=a.bufferOriginalUrl;c.wd=f}else if("flanger"===c)e=new self.ce(b,...e);else if("phaser"===c)e=new self.ee(b,...e);else if("gain"===c)e=
new self.de(b,...e);else if("stereopan"===c)e=new self.ge(b,...e);else if("tremolo"===c)e=new self.he(b,...e);else if("ringmod"===c)e=new self.fe(b,...e);else if("distortion"===c)e=new self.ae(b,...e);else if("compressor"===c)e=new self.Yd(b,...e);else if("analyser"===c)e=new self.Xd(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.ka.get(d);e||(e=[],b.ka.set(d,e));a.Gd=e.length;a.fa=d;e.push(a);xb(b,d);yb(b)}
async function zb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(const e of b.I)e.Aa()&&1===c||!e.Aa()&&2===c?d.push(e):e.j();b.I=d}for(const e of b.ka.values())for(const f of e)f.j();b.ka.clear();b.jc=a.timeScale;b.Oc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);b.va=a.isSilent;b.u.Jb(b.va);b.Zb=a.masterVolume;b.Oa.gain.value=b.Zb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>wb(b,f))));await Promise.all(d);
await Promise.all(a.playing.map(e=>Ab(b,e,c)));T(b)}async function Cb(b,a){try{const c=b.g.suspend(a.time);b.Fd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.u.Hb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Db(d)),b.Fd=!0);await c}catch(c){Db(c)}}
function kb(b){b.Sb||(b.Qc=!1,window.addEventListener("pointerup",b.za,!0),window.addEventListener("touchend",b.za,!0),window.addEventListener("click",b.za,!0),window.addEventListener("keydown",b.za,!0),b.Sb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ja)if(g.gb()===c)return await Eb(g),g;if(f)return null;if(e&&(b.cc||b.Ed)){f=0;for(let h=0,m=b.ja.length;h<m;++h)g=b.ja[h],b.ja[f]=g,g.Aa()?g.j():++f;b.ja.length=f}f="audio/webm; codecs=opus"===d&&!b.Td;e&&f&&(b.Ed=!0);c=!e||b.cc||f?new self.ke(b,a,c,d,e,f):new self.ie(b,a,c,d,e);b.ja.push(c);await Eb(c);b.Ld.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ga()}),b.Ld.add(a));return c}
function Fb(b,a){return(a=b.ka.get(a.toLowerCase()))?a[0].N():b.na()}function xb(b,a){let c=b.na();var d=b.ka.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.S(b.na()):e.S(d[f+1].N())}}for(const f of S(b,a))d=c,e=f.ea||f.F||f.G,e.disconnect(),e.connect(d);b.Ga&&b.Wc===a&&(b.Ga.disconnect(),b.Ga.connect(c))}
function*S(b,a){if(a)for(const c of b.I)b=c.fa,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.$&&!b.$.U()&&(yield b.$)}function Gb(b,a,c){return c?b.u.Qe(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Hb(b,a){let c=0;for(let d=0,e=b.I.length;d<e;++d){const f=b.I[d];b.I[c]=f;f.O===a?f.j():++c}b.I.length=c}
async function nb(b,a,c,d,e,f){for(const g of b.I)if(g.gb()===c&&(g.mc()||f))return g.fa=e,g;a=await P(b,a,c,d,f);e="html5"===a.Jc?new self.je(a.s,a,e):new self.le(a.s,a,e);b.I.push(e);return e}function mb(b,a){let c=b.Ab.get(a);if(!c){let d=null;c={cd:0,promise:new Promise(e=>d=e),resolve:d};b.Ab.set(a,c)}c.cd++}function rb(b,a){a||(a=b.Jd);return(b=b.Ab.get(a))?b.promise:Promise.resolve()}function T(b){if(0<b.Na.size)u(b);else for(const a of b.I)if(!a.H&&!a.U()){u(b);break}}
function Ib(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function yb(b){b.Tc||(b.Tc=!0,Promise.resolve().then(()=>Jb(b)))}function Jb(b){const a={};for(const [c,d]of b.ka)a[c]=d.map(e=>e.fb());k(b,"fxstate",{fxstate:a});b.Tc=!1}
async function Ab(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,q=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await nb(b,d,e,f,h,g)}catch(A){console.error("[Construct] Audio: error loading audio state: ",A);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Ua[0]=f[0],b.Ua[1]=f[1],b.Ua[2]=f[2],f=d.orient,b.Ta[0]=f[0],b.Ta[1]=f[1],b.Ta[2]=f[2],e.setPosition(...b.Ua),e.setOrientation(...b.Ta),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),pb(b,d));c.Play(m,q,p,0);a.isPlaying||c.ib();c.Cc(a)}}}function Db(b){console.error("[Audio] Offline rendering error: ",b)}
self.cb=class extends self.eb{constructor(b){super(b,"audio");this.Oa=this.g=null;this.Sb=this.Qc=!1;this.za=()=>{if(!this.Qc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Sb&&(this.Qc=!0,window.removeEventListener("pointerup",this.za,!0),window.removeEventListener("touchend",this.za,!0),window.removeEventListener("click",this.za,!0),window.removeEventListener("keydown",
this.za,!0),this.Sb=!1)}};this.ja=[];this.I=[];this.$=null;this.Jd="";this.Ld=new Set;this.Kd=-1;this.Ab=new Map;this.Zb=1;this.va=!1;this.ad=0;this.jc=1;this.Oc=0;this.Nd="HRTF";this.yd="inverse";this.Od=600;this.Md=1E4;this.Qd=1;this.aa=[0,0,0];this.Ed=this.cc=!1;this.Td=this.u.qe();this.ka=new Map;this.Na=new Set;this.Fd=this.Tc=!1;this.Wc="";this.Ga=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ga&&this.Ga.disconnect();this.Wc=c.toLowerCase();this.Ga=this.g.createMediaStreamSource(a);this.Ga.connect(Fb(this,
this.Wc))};this.Qb=null;self.C3Audio_GetOutputStream=()=>{this.Qb||(this.Qb=this.g.createMediaStreamDestination(),this.Oa.connect(this.Qb));return this.Qb.stream};self.C3Audio_DOMInterface=this;t(this,[["create-audio-context",a=>jb(this,a)],["play",a=>lb(this,a)],["stop",a=>{a=a.tag;for(const c of S(this,a))c.Ba()}],["stop-all",()=>{for(const a of this.I)a.Ba()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of S(this,c))a?d.ib():d.Ib();T(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;for(const d of S(this,
c))U(d,a)}],["fade-volume",a=>qb(this,a)],["set-master-volume",a=>{this.Zb=a.vol;this.Oa.gain.value=this.Zb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of S(this,c))Kb(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.u.Jb(this.va);for(const c of this.I)c.Nb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of S(this,c))d.uc(a)}],["set-playback-rate",a=>sb(this,a)],["set-stereo-pan",a=>{const c=a.tag;a=a.p;for(const d of S(this,c))R(d,!0),pb(d,a)}],["seek",a=>tb(this,a)],
["preload",a=>ub(this,a)],["unload",a=>vb(this,a)],["unload-all",()=>{for(const a of this.ja)a.j();this.ja.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.I)c.vc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>wb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.ka.get(a.tag);!a||0>c||c>=a.length||(a[c].Y(d,e,f,g),yb(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=this.ka.get(a);
if(c&&c.length){for(const d of c)d.j();this.ka.delete(a);xb(this,a)}}],["tick",a=>{this.jc=a.timeScale;this.Oc=a.gameTime;this.Kd=a.tickCount;if(0!==this.ad)for(var c of this.I)c.Da();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));for(const d of a.instPans){a=d.uid;for(const e of this.I)e.pa===a&&ob(e,d.x,d.y,d.angle)}}],["load-state",a=>zb(this,a)],["offline-render-audio",a=>
Cb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}na(){return this.Oa}Gb(){return this.va}Ca(b){this.u.Ca(b)}Ka(b){this.u.Ka(b)}La(){for(var b of this.Na)b.La();b=this.g.currentTime;for(var a of this.I)a.La(b);a=this.I.filter(c=>!c.H&&!c.U()).map(c=>c.fb());k(this,"state",{tickCount:this.Kd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Na].map(c=>({tag:c.fa,index:c.Gd,peak:c.Va,rms:c.Pd,binCount:c.l.frequencyBinCount,freqBins:c.Dd}))});0===
a.length&&0===this.Na.size&&this.Tb&&(this.u.Pe(this.Ud),this.Tb=!1)}static we(b){return b*ib}static kd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static te(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.ua.bb(self.cb);"use strict";function Eb(b){b.Xb||(b.Xb=b.Bc());return b.Xb}self.fd=class{constructor(b,a,c,d,e){this.s=b;this.We=a;this.Ha=c;this.R=d;this.Te=e;this.Jc="";this.Xb=null}j(){this.Xb=this.s=null}Bc(){}V(){return this.s.V()}pc(){return this.We}gb(){return this.Ha}oc(){return this.R}Aa(){return this.Te}ga(){}};
"use strict";
self.ie=class extends self.fd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Jc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.ub=this.vb=null;this.M.addEventListener("canplaythrough",()=>!0);this.zb=this.V().createGain();this.xb=null;this.M.addEventListener("canplay",()=>{this.vb&&(this.vb(),this.ub=this.vb=null);!this.xb&&this.M&&(this.xb=this.V().createMediaElementSource(this.M),this.xb.connect(this.zb))});this.onended=null;this.M.addEventListener("ended",()=>
{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ha}' error: `,f);this.ub&&(this.ub(f),this.ub=this.vb=null)})}j(){Hb(this.s,this);this.zb.disconnect();this.zb=null;this.xb.disconnect();this.xb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}Bc(){return new Promise((b,a)=>{this.vb=b;this.ub=a;this.M.src=this.Ha})}T(){return this.M}ga(){return this.M.duration}};"use strict";
async function Lb(b){if(b.Ea)return b.Ea;var a=b.s.u;if("cordova"===a.A&&a.md(b.Ha)&&a.Ub)b.Ea=await a.Fb(b.Ha);else{a=await fetch(b.Ha);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ea=await a.arrayBuffer()}}async function Mb(b){if(b.ia)return b.ia;b.ia=await Gb(b.s,b.Ea,b.Ve);b.Ea=null}
self.ke=class extends self.fd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Jc="webaudio";this.ia=this.Ea=null;this.Ve=!!f}j(){Hb(this.s,this);this.ia=this.Ea=null;super.j()}async Bc(){try{await Lb(this),await Mb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ha}': `,b)}}ga(){return this.ia?this.ia.duration:0}};"use strict";let Nb=0;
function Q(b,a){a=!!a;b.rb!==a&&(b.rb=a,b.rb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.s.Nd,b.F.distanceModel=b.s.yd,b.F.refDistance=b.s.Od,b.F.maxDistance=b.s.Md,b.F.rolloffFactor=b.s.Qd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.na())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.na())))}
function R(b,a){a=!!a;b.Vb!==a&&(b.Vb=a,b.Vb?(Q(b,!1),b.ea=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ea),b.ea.connect(b.na())):(b.ea.disconnect(),b.ea=null,b.G.disconnect(),b.G.connect(b.na())))}function pb(b,a){b.Vb&&b.Zc!==a&&(b.ea.pan.value=a,b.Zc=a)}function U(b,a){b.Ia=a;b.G.gain.cancelScheduledValues(0);b.ob=-1;b.G.gain.value=b.qc()}function Kb(b,a){a=!!a;b.Pa!==a&&(b.Pa=a,b.Nb())}
function ob(b,a,c,d){if(b.rb){var e=b.Ua,f=b.Ta,g=Math.cos(d);d=Math.sin(d);if(e[0]!==a||e[1]!==c||0!==e[2])e[0]=a,e[1]=c,e[2]=0,b.F.setPosition(...e);if(f[0]!==g||f[1]!==d||0!==f[2])f[0]=g,f[1]=d,f[2]=0,b.F.setOrientation(...f)}}function V(b){return b.Uc?b.s.Oc:performance.now()/1E3}
self.gd=class{constructor(b,a,c){this.s=b;this.O=a;this.fa=c;this.Ob=Nb++;this.G=this.V().createGain();this.G.connect(this.na());this.F=null;this.rb=!1;this.Ua=[0,0,0];this.Ta=[0,0,0];this.ra=[0,0,0];this.ea=null;this.Vb=!1;this.Zc=0;this.H=!0;this.X=this.sa=this.K=!1;this.Ia=1;this.Pa=!1;this.la=1;b=this.s.ad;this.Uc=1===b&&!this.Aa()||2===b;this.ob=this.pa=-1;this.Sd=!1}j(){this.O=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.ea&&(this.ea.disconnect(),this.ea=null);this.G.disconnect();
this.G=null}V(){return this.s.V()}na(){return Fb(this.s,this.fa)}pc(){return this.O.pc()}gb(){return this.O.gb()}oc(){return this.O.oc()}Aa(){return this.O.Aa()}U(){}mc(){}IsPlaying(){return!this.H&&!this.K&&!this.U()}Ja(){}ga(){return this.O.ga()}Play(){}Ba(){}ib(){}Ib(){}La(b){-1!==this.ob&&b>=this.ob&&(this.ob=-1,this.Sd&&this.Ba(),Ib(this.s,"fade-ended",this.fa,this.Ob))}qc(){const b=this.Ia;return isFinite(b)?b:0}Gb(){return this.s.Gb()}Nb(){}uc(){}Da(){}tc(){}vc(){}rc(){}fb(){var b=this.Ob,
a=this.fa,c=this.ga(),d=this.Ia,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Ua,orient:this.Ta,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ja(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.pc(),bufferUrl:"",bufferType:this.oc(),isMusic:this.Aa(),isLooping:this.X,isMuted:this.Pa,resumePosition:this.rc(),pan:f,stereoPan:this.ea?this.Zc:null}}Cc(b){var a=b.playbackRate;
this.la!==a&&(this.la=a,this.Da());Kb(this,b.isMuted)}};"use strict";
self.je=class extends self.gd{constructor(b,a,c){super(b,a,c);this.O.zb.connect(this.G);this.O.onended=()=>this.Ec()}j(){this.Ba();this.O.zb.disconnect();super.j()}T(){return this.O.T()}Ec(){this.H=!0;this.pa=-1;Ib(this.s,"ended",this.fa,this.Ob)}U(){return this.T().ended}mc(){return this.H?!0:this.U()}Ja(){let b=this.T().currentTime;this.X||(b=Math.min(b,this.ga()));return b}Play(b,a,c){const d=this.T();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.O.gb()}' to position '${c}': `,e)}this.s.Ca(d);this.K=this.H=!1;this.X=b;this.la=1}Ba(){const b=this.T();b.paused||b.pause();this.s.Ka(b);this.H=!0;this.K=!1;this.pa=-1}ib(){if(!(this.K||this.H||this.U())){var b=this.T();b.paused||b.pause();this.s.Ka(b);this.K=!0}}Ib(){!this.K||this.H||this.U()||(this.s.Ca(this.T()),this.K=!1)}Nb(){this.T().muted=this.Pa||this.Gb()}uc(b){b=!!b;this.X!==b&&(this.X=
b,this.T().loop=b)}Da(){let b=this.la;this.Uc&&(b*=this.s.jc);try{this.T().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}tc(b){if(!this.H&&!this.U())try{this.T().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}rc(){return this.Ja()}vc(b){b?this.IsPlaying()?(this.T().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.s.Ca(this.T()),this.sa=!1)}};"use strict";function W(b){b.o&&b.o.disconnect();b.o=null;b.jb=null}
self.le=class extends self.gd{constructor(b,a,c){super(b,a,c);this.o=null;this.ac=d=>this.Ec(d);this.Pc=!0;this.jb=null;this.P=this.bc=this.dc=0;this.Xc=1}j(){this.Ba();W(this);this.ac=null;super.j()}Ec(b){this.K||this.sa||b.target!==this.jb||(this.H=this.Pc=!0,this.pa=-1,W(this),Ib(this.s,"ended",this.fa,this.Ob))}U(){return!this.H&&this.o&&this.o.loop||this.K?!1:this.Pc}mc(){return!this.o||this.H?!0:this.U()}Ja(){let b;b=this.K?this.P:this.bc+(V(this)-this.dc)*this.la;this.X||(b=Math.min(b,this.ga()));
return b}Play(b,a,c,d){this.Xc=1;U(this,a);W(this);this.o=this.V().createBufferSource();this.o.buffer=this.O.ia;this.o.connect(this.G);this.jb=this.o;this.o.onended=this.ac;this.o.loop=b;this.o.start(d,c);this.K=this.H=this.Pc=!1;this.X=b;this.la=1;this.dc=V(this);this.bc=c}Ba(){if(this.o)try{this.o.stop(0)}catch(b){}this.H=!0;this.K=!1;this.pa=-1}ib(){this.K||this.H||this.U()||(this.P=this.Ja(),this.X&&(this.P%=this.ga()),this.K=!0,this.o.stop(0))}Ib(){!this.K||this.H||this.U()||(W(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.O.ia,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.ac,this.o.loop=this.X,U(this,this.Ia),this.Da(),this.o.start(0,this.P),this.dc=V(this),this.bc=this.P,this.K=!1)}qc(){return super.qc()*this.Xc}Nb(){this.Xc=this.Pa||this.Gb()?0:1;U(this,this.Ia)}uc(b){b=!!b;this.X!==b&&(this.X=b,this.o&&(this.o.loop=b))}Da(){let b=this.la;this.Uc&&(b*=this.s.jc);this.o&&(this.o.playbackRate.value=b)}tc(b){this.H||this.U()||(this.K?this.P=b:(this.ib(),this.P=
b,this.Ib()))}rc(){return this.P}vc(b){b?this.IsPlaying()?(this.sa=!0,this.P=this.Ja(),this.X&&(this.P%=this.ga()),this.o.stop(0)):this.sa=!1:this.sa&&(W(this),this.o=this.V().createBufferSource(),this.o.buffer=this.O.ia,this.o.connect(this.G),this.jb=this.o,this.o.onended=this.ac,this.o.loop=this.X,U(this,this.Ia),this.Da(),this.o.start(0,this.P),this.dc=V(this),this.bc=this.P,this.sa=!1)}Cc(b){super.Cc(b);this.P=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.V();this.Gd=-1;this.R=this.fa="";this.m=null}j(){this.g=null}N(){}S(){}fb(){return{type:this.R,tag:this.fa,params:this.m}}}
self.be=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="filter";this.m=[a,c,d,e,f,g];this.v=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.C=this.g.createBiquadFilter();this.C.type=a;this.C.frequency.value=c;this.C.detune.value=d;this.C.Q.value=e;this.C.gain.vlaue=f;this.v.connect(this.C);this.v.connect(this.h);this.C.connect(this.i)}j(){this.v.disconnect();this.C.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.m[2]=a;Y(this,this.C.detune,a,c,d);break;case 3:this.m[3]=a;Y(this,this.C.Q,a,c,d);break;case 4:this.m[4]=a,Y(this,this.C.gain,a,c,d)}}};
self.$d=class extends Z{constructor(b,a,c,d){super(b);this.R="delay";this.m=[a,c,d];this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.wb=X(this);this.W=this.g.createDelay(a);this.W.delayTime.value=a;this.nb=X(this);this.nb.gain.value=c;this.v.connect(this.wb);this.v.connect(this.h);this.wb.connect(this.i);this.wb.connect(this.W);this.W.connect(this.nb);this.nb.connect(this.wb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.wb.disconnect();
this.W.disconnect();this.nb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){const e=self.cb.kd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);Y(this,this.nb.gain,e(a),c,d);break;case 5:this.m[0]=a,Y(this,this.W.delayTime,a,c,d)}}};
self.Zd=class extends Z{constructor(b,a,c,d){super(b);this.R="convolution";this.m=[c,d];this.wd=this.vd="";this.v=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.mb=this.g.createConvolver();this.mb.normalize=c;this.mb.buffer=a;this.v.connect(this.mb);this.v.connect(this.h);this.mb.connect(this.i)}j(){this.v.disconnect();this.mb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}fb(){const b=super.fb();b.bufferOriginalUrl=this.vd;b.bufferUrl="";b.bufferType=this.wd;return b}};
self.ce=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="flanger";this.m=[a,c,d,e,f];this.v=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.pb=X(this);this.pb.gain.value=e;this.W=this.g.createDelay(a+c);this.W.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=X(this);this.L.gain.value=c;this.v.connect(this.W);this.v.connect(this.h);this.W.connect(this.i);this.W.connect(this.pb);this.pb.connect(this.W);this.B.connect(this.L);
this.L.connect(this.W.delayTime);this.B.start(0)}j(){this.B.stop(0);this.v.disconnect();this.W.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.pb.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;Y(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;Y(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,Y(this,this.pb.gain,a/100,c,d)}}};
self.ee=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.R="phaser";this.m=[a,c,d,e,f,g];this.v=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.C=this.g.createBiquadFilter();this.C.type="allpass";this.C.frequency.value=a;this.C.detune.value=c;this.C.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=X(this);this.L.gain.value=e;this.v.connect(this.C);this.v.connect(this.h);this.C.connect(this.i);this.B.connect(this.L);this.L.connect(this.C.frequency);
this.B.start(0)}j(){this.B.stop(0);this.v.disconnect();this.C.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;Y(this,this.C.frequency,a,c,d);break;case 2:this.m[1]=a;Y(this,this.C.detune,a,c,d);
break;case 3:this.m[2]=a;Y(this,this.C.Q,a,c,d);break;case 6:this.m[3]=a;Y(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,Y(this,this.B.frequency,a,c,d)}}};self.de=class extends Z{constructor(b,a){super(b);this.R="gain";this.m=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){const e=self.cb.kd;switch(b){case 4:this.m[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.ge=class extends Z{constructor(b,a){super(b);this.R="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.he=class extends Z{constructor(b,a,c){super(b);this.R="tremolo";this.m=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=X(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.fe=class extends Z{constructor(b,a,c){super(b);this.R="ringmod";this.m=[a,c];this.v=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Cb=X(this);this.Cb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Cb.gain);this.B.start(0);this.v.connect(this.Cb);this.v.connect(this.h);this.Cb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Cb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,Y(this,this.B.frequency,a,c,d)}}};
self.ae=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="distortion";this.m=[a,c,d,e,f];this.v=X(this);this.ic=X(this);this.hc=X(this);b=d;.01>b&&(b=.01);this.ic.gain.value=b;this.hc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.kc=this.g.createWaveShaper();this.Lc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Lc[32768+e]=f,this.Lc[32768-
e-1]=-f;this.kc.curve=this.Lc;this.v.connect(this.ic);this.v.connect(this.h);this.ic.connect(this.kc);this.kc.connect(this.hc);this.hc.connect(this.i)}j(){this.v.disconnect();this.ic.disconnect();this.kc.disconnect();this.hc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}S(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Y(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Yd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.R="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};
self.Xd=class extends Z{constructor(b,a,c){super(b);this.R="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Dd=new Float32Array(this.l.frequencyBinCount);this.Rd=new Uint8Array(a);this.Pd=this.Va=0;b=this.s;b.Na.add(this);T(b)}j(){this.s.Na.delete(this);this.l.disconnect();super.j()}La(){this.l.getFloatFrequencyData(this.Dd);this.l.getByteTimeDomainData(this.Rd);const b=this.l.fftSize;let a=this.Va=0;for(var c=0;c<b;++c){let d=(this.Rd[c]-
128)/128;0>d&&(d=-d);this.Va<d&&(this.Va=d);a+=d*d}c=self.cb.te;this.Va=c(this.Va);this.Pd=c(Math.sqrt(a/b))}S(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Y(){}};"use strict";function Ob(){}function Pb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Qb(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.ua.bb(class extends self.eb{constructor(b){super(b,"browser");this.A="";t(this,[["get-initial-state",a=>{this.A=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Pb(this)],["alert",a=>this.Dc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Fc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Qb(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.nf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.A||"macos-wkwebview"===this.A)self.ua.Mb(!0),this.u.Ic({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===
a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Ob)}}],["exit-fullscreen",()=>{if("windows-webview2"===this.A||"macos-wkwebview"===
this.A)self.ua.Mb(!1),this.u.Ic({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Ob)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=
Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),
c={isOk:!1}}}return c}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}Dc(b){alert(b.message)}Fc(b){b=b.isFocus;if("nwjs"===this.A){const a="nwjs"===this.A?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
